// Generated by sparkling autolink
import Foundation

struct SparklingAutolinkModule {
    let name: String
    let iosModuleName: String?
    let className: String?
}

let sparklingAutolinkBundleId = "app.imkitchen.ios"
let sparklingAutolinkModules: [SparklingAutolinkModule] = [
    SparklingAutolinkModule(name: "sparkling-db", iosModuleName: "Db", className: "DbGetMethod"),
    SparklingAutolinkModule(name: "sparkling-keep-awake", iosModuleName: "KeepAwake", className: "KeepAwakeSetEnabledMethod"),
    SparklingAutolinkModule(name: "sparkling-media", iosModuleName: "", className: ""),
    SparklingAutolinkModule(name: "sparkling-navigation", iosModuleName: "Router", className: "RouterMethod"),
    SparklingAutolinkModule(name: "sparkling-storage", iosModuleName: "SPKStorage", className: "StorageMethod"),
    SparklingAutolinkModule(name: "sparkling-timer-alarm", iosModuleName: "TimerAlarm", className: "TimerAlarmScheduleMethod")
]
