// Generated by sparkling autolink
import Foundation

struct SparklingAutolinkModule {
    let name: String
    let iosModuleName: String?
    let className: String?
}

let sparklingAutolinkBundleId = "app.imkitchen.android"
let sparklingAutolinkModules: [SparklingAutolinkModule] = [
    SparklingAutolinkModule(name: "sparkling-keep-awake", iosModuleName: "", className: ""),
    SparklingAutolinkModule(name: "sparkling-db", iosModuleName: "", className: ""),
    SparklingAutolinkModule(name: "sparkling-navigation", iosModuleName: "Router", className: "RouterMethod"),
    SparklingAutolinkModule(name: "sparkling-media", iosModuleName: "", className: ""),
    SparklingAutolinkModule(name: "sparkling-storage", iosModuleName: "SPKStorage", className: "StorageMethod")
]
