package app.imkitchen.keepawake.setenabled

import com.tiktok.sparkling.method.registry.core.annotation.DefaultType
import com.tiktok.sparkling.method.registry.core.annotation.IDLMethodIntEnum
import com.tiktok.sparkling.method.registry.core.annotation.IDLMethodName
import com.tiktok.sparkling.method.registry.core.annotation.IDLMethodParamField
import com.tiktok.sparkling.method.registry.core.annotation.IDLMethodParamModel
import com.tiktok.sparkling.method.registry.core.annotation.IDLMethodResultModel
import com.tiktok.sparkling.method.registry.core.annotation.IDLMethodStringEnum
import com.tiktok.sparkling.method.registry.core.annotation.MethodParamDefaultValue
import com.tiktok.sparkling.method.registry.core.base.AbsSparklingIDLMethod
import com.tiktok.sparkling.method.registry.core.model.idl.IDLMethodBaseModel
import com.tiktok.sparkling.method.registry.core.model.idl.IDLMethodBaseParamModel
import com.tiktok.sparkling.method.registry.core.model.idl.IDLMethodBaseResultModel


/**
 * GENERATED BY SPARKLING METHOD CLI.
 */
 
abstract class AbsSetEnabledMethodIDL : AbsSparklingIDLMethod<AbsSetEnabledMethodIDL.IDLMethodSetEnabledInputModel, AbsSetEnabledMethodIDL.IDLMethodSetEnabledResultModel>() {

    @IDLMethodName(name = "KeepAwake.setEnabled", params = ["enabled"], results = ["success"])
    final override val name: String = "KeepAwake.setEnabled"

    @IDLMethodParamModel
    interface IDLMethodSetEnabledInputModel : IDLMethodBaseParamModel {

        @get:IDLMethodParamField(required = true, isGetter = true, keyPath = "enabled")
        val enabled: Boolean 
    }

    @IDLMethodResultModel
    interface IDLMethodSetEnabledResultModel: IDLMethodBaseResultModel {

        @get:IDLMethodParamField(required = true, isGetter = true, keyPath = "success")
        @set:IDLMethodParamField(required = true, isGetter = false, keyPath = "success")
        var success: Boolean? 
    }
}
