[package]
name = "imkitchen-web-grocery"
version = "1.10.0"
edition.workspace = true

[dependencies]
axum = { workspace = true }
askama = { workspace = true }
serde = { workspace = true }
tracing = { workspace = true }
imkitchen-types = { path = "../../crates/types", version = "1.10.0" }
imkitchen-web-shared = { path = "../shared", version = "1.10.0" }
