[server]
url = "https://imkitchen.localhost"
host = "0.0.0.0"
port = 3000

[root]
email = "root@imkitchen.localhost"
password = "imkitchen"

[database]
url = "sqlite:imkitchen.db"
max_connections = 5

[jwt]
audience = "https://imkitchen.localhost"
issuer = "imkitchen.localhost"
secret = "TOKEN-NOT-SECURE-MUST-BE-CHANGE"
expiration_days = 14

[features]
premium = true

[monitoring]
log_level = "debug,sqlx=info,tower_http=info"
log_json = false
log_target = true
log_line_number = true

[stripe]
secret_key = ""
publishable_key = ""

[email]
smtp_host = "localhost"
smtp_port = "1025"
smtp_username = ""
smtp_password = ""
from_address = "no-reply@imkitchen.localhost"
contact_address = "contact@imkitchen.localhost"
