# imkitchen Docker Configuration
#
# This file contains Docker Compose-specific defaults.
# Most settings are overridden by environment variables in compose.yml.
#
# Environment variable overrides use the pattern: IMKITCHEN__SECTION__KEY
# Example: IMKITCHEN__JWT__SECRET=your-secret

[server]
# Server host address (listen on all interfaces in container)
host = "0.0.0.0"

# Server port
port = 3000

[database]
# SQLite database URL (persistent volume mount at /var/lib/imkitchen)
url = "sqlite:///var/lib/imkitchen/db.sqlite3"

# Maximum number of database connections
max_connections = 5

[jwt]
# JWT secret key (MUST be overridden via environment variable in production)
# Override with: IMKITCHEN__JWT__SECRET or JWT_SECRET environment variable
secret = "development_secret_key_change_in_production_32chars"

# JWT token expiration in days
expiration_days = 7

[email]
# SMTP Configuration - uses maildev service in Docker Compose
smtp_host = "maildev"
smtp_port = 1025
smtp_username = ""
smtp_password = ""

# Enable/disable TLS for SMTP connections
# Disabled for maildev (local development, no TLS support)
# Override with: IMKITCHEN__EMAIL__SMTP_TLS
smtp_tls = false

# Email sender information
from_email = "noreply@imkitchen.local"
from_name = "imkitchen"

# Base URL for email links (password reset, etc.)
# Override in production: IMKITCHEN__EMAIL__BASE_URL=https://yourdomain.com
base_url = "http://localhost:3000"

[observability]
# OpenTelemetry collector endpoint - uses otel-collector service
otel_endpoint = "http://otel-collector:4319"

# Log level: trace, debug, info, warn, error
log_level = "info"

# Stripe payment processing configuration
# Override these via environment variables (see compose.yml)
[stripe]
secret_key = ""
webhook_secret = ""
price_id = ""

# Web Push Notifications (VAPID) - Story 4.6
# Generate keys with: npx web-push generate-vapid-keys
[vapid]
# VAPID public key (base64url encoded, uncompressed P-256)
# Override with: IMKITCHEN__VAPID__PUBLIC_KEY
public_key = "BB8rIhib51reZc8Yy_MNyeWlTNpYKumwCoB5m1Sd4ggjvo_w3QtfO8XXrzxHPkoVkoVNvCdD50mbl75FYthMnN0"

# VAPID private key (base64url encoded raw key)
# Keep this secret! Override with: IMKITCHEN__VAPID__PRIVATE_KEY
private_key = "gQbVG-hmJgxI1hVm3RkXGEbA_B0mC-Z7vCmy4l5EUrk"

# VAPID subject (mailto: or https: URL)
# Override with: IMKITCHEN__VAPID__SUBJECT
subject = "mailto:contact@imkitchen.local"

# Feature flags for MVP/demo mode
[features]
# Bypass premium restrictions (useful for MVP testing and demos)
# When true, all users are treated as premium (no recipe limits, full features)
# Default: false
# Override with: IMKITCHEN__FEATURES__BYPASS_PREMIUM
bypass_premium = false

# Future configuration sections (not yet implemented):
#
# [minio]
# endpoint = "http://minio:9000"
# access_key = "minioadmin"
# secret_key = ""  # Override with IMKITCHEN__MINIO__SECRET_KEY
