[package]
name = "imkitchen-recipe"
version.workspace = true
edition.workspace = true

[dependencies]
evento.workspace = true
sqlx.workspace = true
tokio.workspace = true
validator.workspace = true
anyhow.workspace = true
serde.workspace = true
bincode.workspace = true
tracing.workspace = true
